#!/bin/bash
export CUDA_VISIBLE_DEVICES=0

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --model FreqMixer \
    --model_id FreqMixer\
    --data traffic \
    --root_path ./dataset/traffic \
    --data_path traffic.csv \
    --features M \
    --seq_len 96 \
    --pred_len 96 \
    --d_model 32 \
    --dropout 0.1 \
    --weight_decay 0.000 \
    --d_factor 6 \
    --p_factor 4 \
    --number_variable 862 \
    --enc_in 862 \
    --dec_in 862 \
    --c_out 862 \
    --des Exp \
    --itr 1 \
    --batch_size 16 \
    --learning_rate 0.005 \
    --train_epochs 20 \
    --patience 5 \
    --percent 100 \
    --patch_size 16 \
    --stride 8 \
    --wv db1 \
    --m 3 \
    --patch_configs "16,8;12,6;12,6;8,4"

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --model FreqMixer \
    --model_id FreqMixer\
    --data traffic \
    --root_path ./dataset/traffic \
    --data_path traffic.csv \
    --features M \
    --seq_len 96 \
    --pred_len 192 \
    --d_model 32 \
    --dropout 0.1 \
    --weight_decay 0.000 \
    --d_factor 6 \
    --p_factor 4 \
    --number_variable 862 \
    --enc_in 862 \
    --dec_in 862 \
    --c_out 862 \
    --des Exp \
    --itr 1 \
    --batch_size 16 \
    --learning_rate 0.005 \
    --train_epochs 20 \
    --patience 5 \
    --percent 100 \
    --patch_size 16 \
    --stride 8 \
    --wv db1 \
    --m 3 \
    --patch_configs "16,8;12,6;12,6;8,4"

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --model FreqMixer \
    --model_id FreqMixer\
    --data traffic \
    --root_path ./dataset/traffic \
    --data_path traffic.csv \
    --features M \
    --seq_len 96 \
    --pred_len 336 \
    --d_model 32 \
    --dropout 0.1 \
    --weight_decay 0.000 \
    --d_factor 6 \
    --p_factor 4 \
    --number_variable 862 \
    --enc_in 862 \
    --dec_in 862 \
    --c_out 862 \
    --des Exp \
    --itr 1 \
    --batch_size 16 \
    --learning_rate 0.005 \
    --train_epochs 20 \
    --patience 5 \
    --percent 100 \
    --patch_size 16 \
    --stride 8 \
    --wv db1 \
    --m 3 \
    --patch_configs "16,8;12,6;12,6;8,4"

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --model FreqMixer \
    --model_id FreqMixer\
    --data traffic \
    --root_path .dataset/traffic \
    --data_path traffic.csv \
    --features M \
    --seq_len 96 \
    --pred_len 720 \
    --d_model 32 \
    --dropout 0.1 \
    --weight_decay 0.000 \
    --d_factor 6 \
    --p_factor 4 \
    --number_variable 862 \
    --enc_in 862 \
    --dec_in 862 \
    --c_out 862 \
    --des Exp \
    --itr 1 \
    --batch_size 16 \
    --learning_rate 0.005 \
    --train_epochs 20 \
    --patience 5 \
    --percent 100 \
    --patch_size 16 \
    --stride 8 \
    --wv db1 \
    --m 3 \
    --patch_configs "16,8;12,6;12,6;8,4"
